[build]
    base = "/opt/build/repo"
    command = "CI=false yarn build"
    commandOrigin = "config"

[environment]
    publish = "/opt/build/repo/build"
    publishOrigin = "config"

[[redirects]]
    from = "/*"
    status = 200
    to = "index.html"
    redirectsOrigin = "config"