[build]
    base = "/"
    command = "CI=false yarn build"
    commandOrigin = "config"

[environment]
    publish = "/build"
    publishOrigin = "config"

[[redirects]]
    from = "/*"
    status = 200
    to = "index.html"
    redirectsOrigin = "config"